version: "3.9"
services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:5000"
    container_name: flask-app
    volumes:
      - ./app:/src
    
volumes:
  postgres_volume: