version: "3.9"
services:
  db:
    image: postgres:14.5
    container_name: db-postgres
    expose:
      - "5432" 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      #POSTGRES_USER と同じDATABASEが作成される
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      - ./app/_init:/docker-entrypoint-initdb.d
    restart: always

  web:
    build: .
    container_name: flask-app
    ports:
      - "8000:5000"
    volumes:
      - ./app:/var/www/pyat
    depends_on:
      - db